version: "3.8"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DATA_ENGINE: "tsm1"
      INFLUXDB_REPORTING_DISABLED: "false"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - influxdb_data:/var/lib/influxdb
  telegraf:
    image: goergch/weathertelegraf:latest
    container_name: telegraf
    environment:
      WEATHER_API_KEY: "INSERT_OPEN_WEATHER_API_KEY_HERE"
      WEATHER_CITY_ID: "2936705" #Ditzingen
      WEATHER_LANGUAGE_ID: "de"
    links:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: "0"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource"

    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - grafana_data:/var/lib/grafana
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086

volumes:
  influxdb_data:
  grafana_data:
  chronograf_data:  
  telegraf_config: